import { ErrorRequestHandler, Response } from "express";
import { z } from "zod";
import { HTTPSTATUS } from "../config/http.config";
import { AppError } from "../shared/utils/app-error";

const formatZodError = (res: Response, error: z.ZodError) => {
    const errors = error?.issues?.map((err) => ({
        field: err.path.join('.'),
        message: err.message,
    }))
    return res.status(HTTPSTATUS.BAD_REQUEST).json({
        message: "Validation failed",
        errors,
    });
}

export const errorHandler: ErrorRequestHandler = (error, req, res, next): any => {
    console.error(`Error occurred on PATH: ${req.path}`, error);

    if (error instanceof z.ZodError) {
        return formatZodError(res, error)
    }

    if (error instanceof AppError) {
        return res.status(error.statusCode).json({
            message: error.message,
            errorCode: error.errorCode
        })
    }

    return res.status(HTTPSTATUS.INTERNAL_SERVER_ERROR).json({
        message: "Internal Server Error",
        error: error?.message || 'An unexpected error occurred',
    })

}